In [54]:
import os
import pandas as pd
import numpy as np
import psycopg
import plotly.graph_objects as go
from plotly.subplots import make_subplots

pd.set_option('display.max_rows', 300)
pd.set_option('display.max_columns', 100)
pd.set_option('display.float_format', '{:.4f}'.format)

In [55]:
DB_DSN = os.getenv("DB_DSN", "postgresql://benjils:snickers@raptor:5432/markets")
conn = psycopg.connect(DB_DSN)

In [56]:
query = """
SELECT *
FROM sec.fut_contracts
"""

df = pd.read_sql(query, conn)
# df['ts'] = pd.to_datetime(df['ts'])
# df.set_index('ts', inplace=True)
df = df.sort_values(by=['contract_month','generic_ticker']).tail(10)
df

/var/folders/1m/gv01tkjs1jlgzsmhr3f1bjyw0000gn/T/ipykernel_99026/3269831819.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,contract,generic_ticker,contract_month,first_notice_date,last_trade_date,first_delivery_date,last_delivery_date,created_at,updated_at,dlv_basket
64,TYH6,TY,2026-03-01,2026-02-27,2026-03-20,2026-03-02,2026-03-31,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.814257+00:00,"{'deliverables': [{'cusip': '91282CFV', 'conve..."
66,USH6,US,2026-03-01,2026-02-27,2026-03-20,2026-03-02,2026-03-31,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.820713+00:00,"{'deliverables': [{'cusip': '912810QQ', 'conve..."
65,UXYH6,UXY,2026-03-01,2026-02-27,2026-03-20,2026-03-02,2026-03-31,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.818420+00:00,"{'deliverables': [{'cusip': '91282CNT', 'conve..."
63,WNH6,WN,2026-03-01,2026-02-27,2026-03-20,2026-03-02,2026-03-31,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.816647+00:00,"{'deliverables': [{'cusip': '912810SX', 'conve..."
62,FVM6,FV,2026-06-01,2026-05-29,2026-06-30,2026-06-01,2026-07-06,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.812231+00:00,"{'deliverables': [{'cusip': '91282CNX', 'conve..."
439,TUM6,TU,2026-06-01,2026-05-29,2026-06-30,2026-06-01,2026-07-06,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.806985+00:00,"{'deliverables': [{'cusip': '91282CGT', 'conve..."
61,TYM6,TY,2026-06-01,2026-05-29,2026-06-18,2026-06-01,2026-06-30,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.808867+00:00,"{'deliverables': [{'cusip': '91282CGM', 'conve..."
60,USM6,US,2026-06-01,2026-05-29,2026-06-18,2026-06-01,2026-06-30,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.804420+00:00,"{'deliverables': [{'cusip': '912810QS', 'conve..."
43,UXYM6,UXY,2026-06-01,2026-05-29,2026-06-18,2026-06-01,2026-06-30,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.801282+00:00,"{'deliverables': [{'cusip': '91282CPJ', 'conve..."
22,WNM6,WN,2026-06-01,2026-05-29,2026-06-18,2026-06-01,2026-06-30,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.037936+00:00,"{'deliverables': [{'cusip': '912810SZ', 'conve..."

In [57]:
print(df.iloc[0])
pd.json_normalize(df['dlv_basket'].iloc[0], record_path='deliverables')

contract                                                            TYH6
generic_ticker                                                        TY
contract_month                                                2026-03-01
first_notice_date                                             2026-02-27
last_trade_date                                               2026-03-20
first_delivery_date                                           2026-03-02
last_delivery_date                                            2026-03-31
created_at                              2026-01-13 04:17:02.322932+00:00
updated_at                              2026-01-14 04:19:46.814257+00:00
dlv_basket             {'deliverables': [{'cusip': '91282CFV', 'conve...
Name: 64, dtype: object

      cusip  conversion_factor
0  91282CFV             0.9003
1  91282CGM             0.8628
2  91282CHC             0.8517
3  91282CHT             0.8765
4  91282CJJ             0.9105
5  91282CJZ             0.8774
6  91282CNZ             0.8870
7  91282CPF             0.8804
8  91282CPM             0.8804
9  91282CPQ             0.8834

In [53]:
conn.close()