In [9]:
import os
import pandas as pd
import numpy as np
import psycopg
import plotly.graph_objects as go
from plotly.subplots import make_subplots

pd.set_option('display.max_rows', 300)
pd.set_option('display.max_columns', 100)
pd.set_option('display.float_format', '{:.4f}'.format)

In [10]:
DB_DSN = os.getenv("DB_DSN", "postgresql://benjils:snickers@raptor:5432/markets")
conn = psycopg.connect(DB_DSN)

In [15]:
query = """
SELECT *
FROM sec.fut_contracts
"""

df = pd.read_sql(query, conn)
# df['ts'] = pd.to_datetime(df['ts'])
# df.set_index('ts', inplace=True)
df = df.sort_values(by=['contract_month','generic_ticker'])
df.tail(6)

/var/folders/1m/gv01tkjs1jlgzsmhr3f1bjyw0000gn/T/ipykernel_4685/3730630256.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,contract,generic_ticker,contract_month,first_notice_date,last_trade_date,first_delivery_date,last_delivery_date,created_at,updated_at,dlv_basket
62,FVM6,FV,2026-06-01,2026-05-29,2026-06-30,2026-06-01,2026-07-06,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.812231+00:00,"{'deliverables': [{'cusip': '91282CNX', 'conve..."
439,TUM6,TU,2026-06-01,2026-05-29,2026-06-30,2026-06-01,2026-07-06,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.806985+00:00,"{'deliverables': [{'cusip': '91282CGT', 'conve..."
61,TYM6,TY,2026-06-01,2026-05-29,2026-06-18,2026-06-01,2026-06-30,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.808867+00:00,"{'deliverables': [{'cusip': '91282CGM', 'conve..."
60,USM6,US,2026-06-01,2026-05-29,2026-06-18,2026-06-01,2026-06-30,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.804420+00:00,"{'deliverables': [{'cusip': '912810QS', 'conve..."
43,UXYM6,UXY,2026-06-01,2026-05-29,2026-06-18,2026-06-01,2026-06-30,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.801282+00:00,"{'deliverables': [{'cusip': '91282CPJ', 'conve..."
22,WNM6,WN,2026-06-01,2026-05-29,2026-06-18,2026-06-01,2026-06-30,2026-01-13 04:17:02.322932+00:00,2026-01-14 04:19:46.037936+00:00,"{'deliverables': [{'cusip': '912810SZ', 'conve..."

In [20]:
print(df.iloc[-1])
pd.json_normalize(df['dlv_basket'].iloc[-1], record_path='deliverables')

contract                                                            WNM6
generic_ticker                                                        WN
contract_month                                                2026-06-01
first_notice_date                                             2026-05-29
last_trade_date                                               2026-06-18
first_delivery_date                                           2026-06-01
last_delivery_date                                            2026-06-30
created_at                              2026-01-13 04:17:02.322932+00:00
updated_at                              2026-01-14 04:19:46.037936+00:00
dlv_basket             {'deliverables': [{'cusip': '912810SZ', 'conve...
Name: 22, dtype: object

       cusip  conversion_factor
0   912810SZ             0.4854
1   912810TB             0.4670
2   912810TD             0.5134
3   912810TG             0.5928
4   912810TJ             0.6075
5   912810TL             0.7372
6   912810TN             0.6868
7   912810TR             0.6855
8   912810TT             0.7508
9   912810TV             0.8332
10  912810TX             0.7657
11  912810UA             0.8152
12  912810UC             0.7641
13  912810UE             0.7970
14  912810UG             0.8133
15  912810UK             0.8297
16  912810UM             0.8292
17  912810UP             0.8114

In [19]:
conn.close()