In [1]:
import os
import pandas as pd
import numpy as np
import psycopg
import plotly.graph_objects as go
from plotly.subplots import make_subplots

pd.set_option('display.max_rows', 300)
pd.set_option('display.max_columns', 100)
pd.set_option('display.float_format', '{:.4f}'.format)

In [3]:
DB_DSN = os.getenv("DB_DSN", "postgresql://benjils:snickers@raptor:5432/markets")
conn = psycopg.connect(DB_DSN)

In [4]:
query = """
SELECT schema_name
FROM information_schema.schemata
ORDER BY schema_name
"""
df_schemas = pd.read_sql(query, conn)
df_schemas

/var/folders/1m/gv01tkjs1jlgzsmhr3f1bjyw0000gn/T/ipykernel_24738/1682484226.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_schemas = pd.read_sql(query, conn)

                 schema_name
0         _timescaledb_cache
1       _timescaledb_catalog
2        _timescaledb_config
3         _timescaledb_debug
4     _timescaledb_functions
5      _timescaledb_internal
6         information_schema
7                         md
8                 pg_catalog
9                  pg_temp_4
10                 pg_temp_6
11                 pg_temp_7
12                  pg_toast
13           pg_toast_temp_4
14           pg_toast_temp_6
15           pg_toast_temp_7
16                    public
17                       sec
18  timescaledb_experimental
19   timescaledb_information
20      toolkit_experimental

In [5]:
query = """
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'sec'
ORDER BY table_name, ordinal_position
"""
sch = pd.read_sql(query, conn)
sch

/var/folders/1m/gv01tkjs1jlgzsmhr3f1bjyw0000gn/T/ipykernel_24738/2139700717.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sch = pd.read_sql(query, conn)

,table_name,column_name,data_type
0,auctioned_securities,record_date,timestamp with time zone
1,auctioned_securities,cusip,text
2,auctioned_securities,security_type,text
3,auctioned_securities,security_term,text
4,auctioned_securities,auction_date,timestamp with time zone
5,auctioned_securities,issue_date,timestamp with time zone
6,auctioned_securities,maturity_date,timestamp with time zone
7,auctioned_securities,price_per100,text
8,auctioned_securities,accrued_int_per100,text
9,auctioned_securities,accrued_int_per1000,text
10,auctioned_securities,adj_accrued_int_per1000,text
11,auctioned_securities,adj_price,text
12,auctioned_securities,allocation_pctage,text
13,auctioned_securities,allocation_pctage_decimals,text
14,auctioned_securities,announcemtd_cusip,text
15,auctioned_securities,announcemt_date,text
16,auctioned_securities,auction_format,text
17,auctioned_securities,avg_med_discnt_rate,text
18,auctioned_securities,avg_med_investment_rate,text
19,auctioned_securities,avg_med_price,text
20,auctioned_securities,avg_med_discnt_margin,text
21,auctioned_securities,avg_med_yield,double precision
22,auctioned_securities,back_dated,text
23,auctioned_securities,back_dated_date,text
24,auctioned_securities,bid_to_cover_ratio,double precision
25,auctioned_securities,callable,text
26,auctioned_securities,call_date,timestamp with time zone
27,auctioned_securities,called_date,text
28,auctioned_securities,cash_management_bill_cmb,text
29,auctioned_securities,closing_time_comp,text
30,auctioned_securities,closing_time_noncomp,text
31,auctioned_securities,comp_accepted,text
32,auctioned_securities,comp_bid_decimals,text
33,auctioned_securities,comp_tendered,text
34,auctioned_securities,comp_tenders_accepted,text
35,auctioned_securities,corpus_cusip,text
36,auctioned_securities,cpi_base_reference_period,text
37,auctioned_securities,currently_outstanding,text
38,auctioned_securities,dated_date,timestamp with time zone
39,auctioned_securities,direct_bidder_accepted,text
40,auctioned_securities,direct_bidder_tendered,text
41,auctioned_securities,est_pub_held_mat_by_type_amt,text
42,auctioned_securities,fima_included,text
43,auctioned_securities,fima_noncomp_accepted,text
44,auctioned_securities,fima_noncomp_tendered,text
45,auctioned_securities,first_int_period,text
46,auctioned_securities,first_int_payment_date,timestamp with time zone
47,auctioned_securities,floating_rate,text
48,auctioned_securities,frn_index_determination_date,text
49,auctioned_securities,frn_index_determination_rate,text
50,auctioned_securities,high_discnt_rate,text
51,auctioned_securities,high_investment_rate,text
52,auctioned_securities,high_price,text
53,auctioned_securities,high_discnt_margin,text
54,auctioned_securities,high_yield,double precision
55,auctioned_securities,index_ratio_on_issue_date,text
56,auctioned_securities,indirect_bidder_accepted,text
57,auctioned_securities,indirect_bidder_tendered,text
58,auctioned_securities,int_payment_frequency,text
59,auctioned_securities,int_rate,double precision
60,auctioned_securities,low_discnt_rate,text
61,auctioned_securities,low_investment_rate,text
62,auctioned_securities,low_price,text
63,auctioned_securities,low_discnt_margin,text
64,auctioned_securities,low_yield,double precision
65,auctioned_securities,mat_date,text
66,auctioned_securities,max_comp_award,text
67,auctioned_securities,max_noncomp_award,text
68,auctioned_securities,max_single_bid,text
69,auctioned_securities,min_bid_amt,text
70,auctioned_securities,min_strip_amt,text
71,auctioned_securities,min_to_issue,text
72,auctioned_securities,multiples_to_bid,text
73,auctioned_securities,multiples_to_issue,text
74,auctioned_securities,nlp_exclusion_amt,text
75,auctioned_securities,nlp_reporting_threshold,text
76,auctioned_securities,noncomp_accepted,text
77,auctioned_securities,noncomp_tenders_accepted,text
78,auctioned_securities,offering_amt,text
79,auctioned_securities,original_cusip,text
80,auctioned_securities,original_dated_date,text
81,auctioned_securities,original_issue_date,text
82,auctioned_securities,original_security_term,text
83,auctioned_securities,pdf_filenm_announcemt,text
84,auctioned_securities,pdf_filenm_comp_results,text
85,auctioned_securities,pdf_filenm_noncomp_results,text
86,auctioned_securities,primary_dealer_accepted,text
87,auctioned_securities,primary_dealer_tendered,text
88,auctioned_securities,ref_cpi_on_dated_date,text
89,auctioned_securities,ref_cpi_on_issue_date,text
90,auctioned_securities,reopening,text
91,auctioned_securities,security_term_day_month,text
92,auctioned_securities,security_term_week_year,text
93,auctioned_securities,series,text
94,auctioned_securities,soma_accepted,text
95,auctioned_securities,soma_holdings,text
96,auctioned_securities,soma_included,text
97,auctioned_securities,soma_tendered,text
98,auctioned_securities,spread,text
99,auctioned_securities,std_int_payment_per1000,text
100,auctioned_securities,strippable,text
101,auctioned_securities,tiin_conversion_factor_per1000,text
102,auctioned_securities,total_accepted,double precision
103,auctioned_securities,total_tendered,double precision
104,auctioned_securities,treas_retail_accepted,text
105,auctioned_securities,treas_retail_tenders_accepted,text
106,auctioned_securities,unadj_accrued_int_per1000,text
107,auctioned_securities,unadj_price,text
108,auctioned_securities,xml_filenm_announcemt,text
109,auctioned_securities,xml_filenm_comp_results,text
110,auctioned_securities,inflation_index_security,text
111,auctioned_securities,tint_cusip_1,text
112,auctioned_securities,tint_cusip_2,text
113,fut_contracts,contract,text
114,fut_contracts,generic_ticker,text
115,fut_contracts,contract_month,date
116,fut_contracts,first_notice_date,date
117,fut_contracts,last_trade_date,date
118,fut_contracts,first_delivery_date,date
119,fut_contracts,last_delivery_date,date
120,fut_contracts,created_at,timestamp with time zone
121,fut_contracts,updated_at,timestamp with time zone
122,fut_contracts,dlv_basket,jsonb

In [6]:
query = """
select distinct h.ts, h.tenor, h.asset_class, h.cusip, h.status, h.yld_ytm_mid, 
date(s.maturity_date) as maturity_date, date(s.issue_date) as issue_date, s.original_security_term
, s.floating_rate
from md.headline h
left join sec.auctioned_securities s on h.cusip = s.cusip and s.reopening = 'No'
where ts > '20251101'
and asset_class = 'nominal'
and status in ('c','o')
and tenor = '2-Year'
order by ts, status
"""
hl = pd.read_sql(query, conn)
hl.tail(50)

/var/folders/1m/gv01tkjs1jlgzsmhr3f1bjyw0000gn/T/ipykernel_24738/613324589.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  hl = pd.read_sql(query, conn)

,ts,tenor,asset_class,cusip,status,yld_ytm_mid,maturity_date,issue_date,original_security_term,floating_rate
0,2025-11-03,2-Year,nominal,91282CPG0,c,3.9350,2027-10-31,2025-10-31,2-Year,Yes
1,2025-11-03,2-Year,nominal,91282CPE5,o,3.6020,2027-10-31,2025-10-31,2-Year,No
2,2025-11-04,2-Year,nominal,91282CPG0,c,3.9360,2027-10-31,2025-10-31,2-Year,Yes
3,2025-11-04,2-Year,nominal,91282CPE5,o,3.5590,2027-10-31,2025-10-31,2-Year,No
4,2025-11-05,2-Year,nominal,91282CPG0,c,3.9310,2027-10-31,2025-10-31,2-Year,Yes
5,2025-11-05,2-Year,nominal,91282CPE5,o,3.6170,2027-10-31,2025-10-31,2-Year,No
6,2025-11-06,2-Year,nominal,91282CPG0,c,3.9370,2027-10-31,2025-10-31,2-Year,Yes
7,2025-11-06,2-Year,nominal,91282CPE5,o,3.5570,2027-10-31,2025-10-31,2-Year,No
8,2025-11-07,2-Year,nominal,91282CPG0,c,3.9370,2027-10-31,2025-10-31,2-Year,Yes
9,2025-11-07,2-Year,nominal,91282CPE5,o,3.5620,2027-10-31,2025-10-31,2-Year,No
10,2025-11-10,2-Year,nominal,91282CPG0,c,4.0220,2027-10-31,2025-10-31,2-Year,Yes
11,2025-11-10,2-Year,nominal,91282CPE5,o,3.5910,2027-10-31,2025-10-31,2-Year,No
12,2025-11-11,2-Year,nominal,91282CPG0,c,4.0220,2027-10-31,2025-10-31,2-Year,Yes
13,2025-11-11,2-Year,nominal,91282CPE5,o,3.5530,2027-10-31,2025-10-31,2-Year,No
14,2025-11-12,2-Year,nominal,91282CPG0,c,4.0230,2027-10-31,2025-10-31,2-Year,Yes
15,2025-11-12,2-Year,nominal,91282CPE5,o,3.5680,2027-10-31,2025-10-31,2-Year,No
16,2025-11-13,2-Year,nominal,91282CPG0,c,4.0190,2027-10-31,2025-10-31,2-Year,Yes
17,2025-11-13,2-Year,nominal,91282CPE5,o,3.5930,2027-10-31,2025-10-31,2-Year,No
18,2025-11-14,2-Year,nominal,91282CPG0,c,4.0150,2027-10-31,2025-10-31,2-Year,Yes
19,2025-11-14,2-Year,nominal,91282CPE5,o,3.6080,2027-10-31,2025-10-31,2-Year,No
20,2025-11-17,2-Year,nominal,91282CPG0,c,3.9820,2027-10-31,2025-10-31,2-Year,Yes
21,2025-11-17,2-Year,nominal,91282CPE5,o,3.6020,2027-10-31,2025-10-31,2-Year,No
22,2025-11-18,2-Year,nominal,91282CPG0,c,3.9720,2027-10-31,2025-10-31,2-Year,Yes
23,2025-11-18,2-Year,nominal,91282CPE5,o,3.5730,2027-10-31,2025-10-31,2-Year,No
24,2025-11-19,2-Year,nominal,91282CPG0,c,3.9720,2027-10-31,2025-10-31,2-Year,Yes
25,2025-11-19,2-Year,nominal,91282CPE5,o,3.6000,2027-10-31,2025-10-31,2-Year,No
26,2025-11-20,2-Year,nominal,91282CPG0,c,3.9780,2027-10-31,2025-10-31,2-Year,Yes
27,2025-11-20,2-Year,nominal,91282CPE5,o,3.5470,2027-10-31,2025-10-31,2-Year,No
28,2025-11-21,2-Year,nominal,91282CPG0,c,3.9770,2027-10-31,2025-10-31,2-Year,Yes
29,2025-11-21,2-Year,nominal,91282CPE5,o,3.5100,2027-10-31,2025-10-31,2-Year,No
30,2025-11-24,2-Year,nominal,91282CPL9,c,3.4850,2027-11-30,2025-12-01,2-Year,No
31,2025-11-24,2-Year,nominal,91282CPG0,o,3.9810,2027-10-31,2025-10-31,2-Year,Yes
32,2025-11-25,2-Year,nominal,91282CPL9,c,3.4590,2027-11-30,2025-12-01,2-Year,No
33,2025-11-25,2-Year,nominal,91282CPG0,o,3.9800,2027-10-31,2025-10-31,2-Year,Yes
34,2025-11-26,2-Year,nominal,91282CPL9,c,3.4750,2027-11-30,2025-12-01,2-Year,No
35,2025-11-26,2-Year,nominal,91282CPG0,o,3.9820,2027-10-31,2025-10-31,2-Year,Yes
36,2025-11-27,2-Year,nominal,91282CPL9,c,3.4910,2027-11-30,2025-12-01,2-Year,No
37,2025-11-27,2-Year,nominal,91282CPG0,o,3.9820,2027-10-31,2025-10-31,2-Year,Yes
38,2025-11-28,2-Year,nominal,91282CPL9,c,3.4930,2027-11-30,2025-12-01,2-Year,No
39,2025-11-28,2-Year,nominal,91282CPG0,o,3.9470,2027-10-31,2025-10-31,2-Year,Yes
40,2025-12-01,2-Year,nominal,91282CPL9,c,3.5280,2027-11-30,2025-12-01,2-Year,No
41,2025-12-01,2-Year,nominal,91282CPG0,o,3.9390,2027-10-31,2025-10-31,2-Year,Yes
42,2025-12-02,2-Year,nominal,91282CPL9,c,3.5060,2027-11-30,2025-12-01,2-Year,No
43,2025-12-02,2-Year,nominal,91282CPG0,o,3.9480,2027-10-31,2025-10-31,2-Year,Yes
44,2025-12-03,2-Year,nominal,91282CPL9,c,3.4920,2027-11-30,2025-12-01,2-Year,No
45,2025-12-03,2-Year,nominal,91282CPG0,o,3.9510,2027-10-31,2025-10-31,2-Year,Yes
46,2025-12-04,2-Year,nominal,91282CPL9,c,3.5150,2027-11-30,2025-12-01,2-Year,No
47,2025-12-04,2-Year,nominal,91282CPG0,o,3.9360,2027-10-31,2025-10-31,2-Year,Yes
48,2025-12-05,2-Year,nominal,91282CPL9,c,3.5620,2027-11-30,2025-12-01,2-Year,No
49,2025-12-05,2-Year,nominal,91282CPG0,o,3.9410,2027-10-31,2025-10-31,2-Year,Yes

In [7]:
df = hl.pivot(index='ts', columns='tenor', values='yld_ytm_mid')[['2-Year','3-Year','5-Year','7-Year','10-Year','20-Year','30-Year']]
df['2y10y'] = 100*(df['10-Year'] - df['2-Year'])
df

ValueError: Index contains duplicate entries, cannot reshape